### PR TITLE
Switch to console-log-level

### PR DESCRIPTION
**Pull request by Qard**
Bunyan has an optional dependency on dtrace-provider, which is a native module. With optional dependencies, it's fine for them to fail to install. On Windows, however, the build process uses node-gyp and therefore fails the install with a big scary error.

To avoid the build error, I've switched to a simple console logger.

NOTE: I chose to just make a new PR for this to replace the work in #61.

Fixes #61

### CODE REVIEW

**Comment by fieldju** [comment]
Can you utilize the prefix functionality and take on a timestamp to the log message please.
https://github.com/watson/console-log-level/blob/master/index.js#L36

**Comment by Qard** [comment]
Added a prefix function. What do you think? Is that sufficient, or would you prefer a different prefix?

**Comment by fieldju** [comment]
> Added a prefix function. What do you think? Is that sufficient, or would you prefer a different prefix?

Im pretty sure that should work with Splunk, and will defiantly be useful for dev if manually tailing logs etc.

**Comment by fieldju** [comment]
https://travis-ci.org/yaorg/node-measured/jobs/508651449

**Comment by Qard** [comment]
Force-pushed to appease the linter. 😅

**Comment by fieldju** [comment]
Ok, I gave my approval, are you going to merge and cut the v1.41.0 release?

**Comment by Qard** [comment]
Sorry for the lack of response. I'm in Europe right now, so that last commit was after midnight here. I just went to sleep after pushing that. 😅 

Thanks for landing it. It'll be great to be rid of the dtrace-provider install failures! 🙀

**Pull request merged**
